//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomsuWcf
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZwebKomsuS_001", Namespace="http://schemas.datacontract.org/2004/07/Sultanlar.WCF.KomsuC001")]
    public partial class ZwebKomsuS_001 : object
    {
        
        private string categorycodeFieldField;
        
        private string categorynameFieldField;
        
        private string isactiveFieldField;
        
        private string parentcodeFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string categorycodeField
        {
            get
            {
                return this.categorycodeFieldField;
            }
            set
            {
                this.categorycodeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string categorynameField
        {
            get
            {
                return this.categorynameFieldField;
            }
            set
            {
                this.categorynameFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string isactiveField
        {
            get
            {
                return this.isactiveFieldField;
            }
            set
            {
                this.isactiveFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string parentcodeField
        {
            get
            {
                return this.parentcodeFieldField;
            }
            set
            {
                this.parentcodeFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZwebKomsuS_002", Namespace="http://schemas.datacontract.org/2004/07/Sultanlar.WCF.KomsuC002")]
    public partial class ZwebKomsuS_002 : object
    {
        
        private string associationCodeFieldField;
        
        private string brandFieldField;
        
        private string categoryFieldField;
        
        private string priceUnitFieldField;
        
        private string productCodeFieldField;
        
        private string productDetailFieldField;
        
        private string productNameFieldField;
        
        private string stockUnitFieldField;
        
        private string taxRateFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string associationCodeField
        {
            get
            {
                return this.associationCodeFieldField;
            }
            set
            {
                this.associationCodeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string brandField
        {
            get
            {
                return this.brandFieldField;
            }
            set
            {
                this.brandFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string categoryField
        {
            get
            {
                return this.categoryFieldField;
            }
            set
            {
                this.categoryFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string priceUnitField
        {
            get
            {
                return this.priceUnitFieldField;
            }
            set
            {
                this.priceUnitFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string productCodeField
        {
            get
            {
                return this.productCodeFieldField;
            }
            set
            {
                this.productCodeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string productDetailField
        {
            get
            {
                return this.productDetailFieldField;
            }
            set
            {
                this.productDetailFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string productNameField
        {
            get
            {
                return this.productNameFieldField;
            }
            set
            {
                this.productNameFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string stockUnitField
        {
            get
            {
                return this.stockUnitFieldField;
            }
            set
            {
                this.stockUnitFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string taxRateField
        {
            get
            {
                return this.taxRateFieldField;
            }
            set
            {
                this.taxRateFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZwebKomsuS_003", Namespace="http://schemas.datacontract.org/2004/07/Sultanlar.WCF.KomsuC003")]
    public partial class ZwebKomsuS_003 : object
    {
        
        private string attributes1FieldField;
        
        private string attributes2FieldField;
        
        private string barcodeFieldField;
        
        private string productCodeFieldField;
        
        private decimal stockFieldField;
        
        private bool stockFieldSpecifiedField;
        
        private string subproductcodeFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string attributes1Field
        {
            get
            {
                return this.attributes1FieldField;
            }
            set
            {
                this.attributes1FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string attributes2Field
        {
            get
            {
                return this.attributes2FieldField;
            }
            set
            {
                this.attributes2FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string barcodeField
        {
            get
            {
                return this.barcodeFieldField;
            }
            set
            {
                this.barcodeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string productCodeField
        {
            get
            {
                return this.productCodeFieldField;
            }
            set
            {
                this.productCodeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal stockField
        {
            get
            {
                return this.stockFieldField;
            }
            set
            {
                this.stockFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool stockFieldSpecified
        {
            get
            {
                return this.stockFieldSpecifiedField;
            }
            set
            {
                this.stockFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string subproductcodeField
        {
            get
            {
                return this.subproductcodeFieldField;
            }
            set
            {
                this.subproductcodeFieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Werks", Namespace="http://schemas.datacontract.org/2004/07/Sultanlar.WCF.KomsuC004")]
    public partial class Werks : object
    {
        
        private string werks1FieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string werks1Field
        {
            get
            {
                return this.werks1FieldField;
            }
            set
            {
                this.werks1FieldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZwebKomsuS_004", Namespace="http://schemas.datacontract.org/2004/07/Sultanlar.WCF.KomsuC004")]
    public partial class ZwebKomsuS_004 : object
    {
        
        private string priceunitFieldField;
        
        private string productcodeFieldField;
        
        private decimal purchasePriceFieldField;
        
        private bool purchasePriceFieldSpecifiedField;
        
        private decimal salePriceFieldField;
        
        private bool salePriceFieldSpecifiedField;
        
        private decimal sellerPriceFieldField;
        
        private bool sellerPriceFieldSpecifiedField;
        
        private string taxRateFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string priceunitField
        {
            get
            {
                return this.priceunitFieldField;
            }
            set
            {
                this.priceunitFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string productcodeField
        {
            get
            {
                return this.productcodeFieldField;
            }
            set
            {
                this.productcodeFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal purchasePriceField
        {
            get
            {
                return this.purchasePriceFieldField;
            }
            set
            {
                this.purchasePriceFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool purchasePriceFieldSpecified
        {
            get
            {
                return this.purchasePriceFieldSpecifiedField;
            }
            set
            {
                this.purchasePriceFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal salePriceField
        {
            get
            {
                return this.salePriceFieldField;
            }
            set
            {
                this.salePriceFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool salePriceFieldSpecified
        {
            get
            {
                return this.salePriceFieldSpecifiedField;
            }
            set
            {
                this.salePriceFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal sellerPriceField
        {
            get
            {
                return this.sellerPriceFieldField;
            }
            set
            {
                this.sellerPriceFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool sellerPriceFieldSpecified
        {
            get
            {
                return this.sellerPriceFieldSpecifiedField;
            }
            set
            {
                this.sellerPriceFieldSpecifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string taxRateField
        {
            get
            {
                return this.taxRateFieldField;
            }
            set
            {
                this.taxRateFieldField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KomsuWcf.IKomsu")]
    public interface IKomsu
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKomsu/DoWork", ReplyAction="http://tempuri.org/IKomsu/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKomsu/DoWork", ReplyAction="http://tempuri.org/IKomsu/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKomsu/komsu001", ReplyAction="http://tempuri.org/IKomsu/komsu001Response")]
        KomsuWcf.ZwebKomsuS_001[] komsu001(string Matnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKomsu/komsu001", ReplyAction="http://tempuri.org/IKomsu/komsu001Response")]
        System.Threading.Tasks.Task<KomsuWcf.ZwebKomsuS_001[]> komsu001Async(string Matnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKomsu/komsu002", ReplyAction="http://tempuri.org/IKomsu/komsu002Response")]
        KomsuWcf.ZwebKomsuS_002[] komsu002(string Matnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKomsu/komsu002", ReplyAction="http://tempuri.org/IKomsu/komsu002Response")]
        System.Threading.Tasks.Task<KomsuWcf.ZwebKomsuS_002[]> komsu002Async(string Matnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKomsu/komsu003", ReplyAction="http://tempuri.org/IKomsu/komsu003Response")]
        KomsuWcf.ZwebKomsuS_003[] komsu003(string Matnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKomsu/komsu003", ReplyAction="http://tempuri.org/IKomsu/komsu003Response")]
        System.Threading.Tasks.Task<KomsuWcf.ZwebKomsuS_003[]> komsu003Async(string Matnr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKomsu/komsu004", ReplyAction="http://tempuri.org/IKomsu/komsu004Response")]
        KomsuWcf.ZwebKomsuS_004[] komsu004(string Matnr, KomsuWcf.Werks Werks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKomsu/komsu004", ReplyAction="http://tempuri.org/IKomsu/komsu004Response")]
        System.Threading.Tasks.Task<KomsuWcf.ZwebKomsuS_004[]> komsu004Async(string Matnr, KomsuWcf.Werks Werks);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IKomsuChannel : KomsuWcf.IKomsu, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class KomsuClient : System.ServiceModel.ClientBase<KomsuWcf.IKomsu>, KomsuWcf.IKomsu
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KomsuClient() : 
                base(KomsuClient.GetDefaultBinding(), KomsuClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MyService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KomsuClient(EndpointConfiguration endpointConfiguration) : 
                base(KomsuClient.GetBindingForEndpoint(endpointConfiguration), KomsuClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KomsuClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KomsuClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KomsuClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KomsuClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KomsuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void DoWork()
        {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync()
        {
            return base.Channel.DoWorkAsync();
        }
        
        public KomsuWcf.ZwebKomsuS_001[] komsu001(string Matnr)
        {
            return base.Channel.komsu001(Matnr);
        }
        
        public System.Threading.Tasks.Task<KomsuWcf.ZwebKomsuS_001[]> komsu001Async(string Matnr)
        {
            return base.Channel.komsu001Async(Matnr);
        }
        
        public KomsuWcf.ZwebKomsuS_002[] komsu002(string Matnr)
        {
            return base.Channel.komsu002(Matnr);
        }
        
        public System.Threading.Tasks.Task<KomsuWcf.ZwebKomsuS_002[]> komsu002Async(string Matnr)
        {
            return base.Channel.komsu002Async(Matnr);
        }
        
        public KomsuWcf.ZwebKomsuS_003[] komsu003(string Matnr)
        {
            return base.Channel.komsu003(Matnr);
        }
        
        public System.Threading.Tasks.Task<KomsuWcf.ZwebKomsuS_003[]> komsu003Async(string Matnr)
        {
            return base.Channel.komsu003Async(Matnr);
        }
        
        public KomsuWcf.ZwebKomsuS_004[] komsu004(string Matnr, KomsuWcf.Werks Werks)
        {
            return base.Channel.komsu004(Matnr, Werks);
        }
        
        public System.Threading.Tasks.Task<KomsuWcf.ZwebKomsuS_004[]> komsu004Async(string Matnr, KomsuWcf.Werks Werks)
        {
            return base.Channel.komsu004Async(Matnr, Werks);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MyService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TransportSecurityBindingElement userNameOverTransportSecurityBindingElement = System.ServiceModel.Channels.SecurityBindingElement.CreateUserNameOverTransportBindingElement();
                userNameOverTransportSecurityBindingElement.MessageSecurityVersion = System.ServiceModel.MessageSecurityVersion.WSSecurity11WSTrustFebruary2005WSSecureConversationFebruary2005WSSecurityPolicy11BasicSecurityProfile10;
                result.Elements.Add(userNameOverTransportSecurityBindingElement);
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MyService))
            {
                return new System.ServiceModel.EndpointAddress("https://ittihadteknoloji.com.tr/wcf/Komsu.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KomsuClient.GetBindingForEndpoint(EndpointConfiguration.MyService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KomsuClient.GetEndpointAddress(EndpointConfiguration.MyService);
        }
        
        public enum EndpointConfiguration
        {
            
            MyService,
        }
    }
}
