//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sultanlar.UI.QuantumWeb {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuantumWeb.svcLibraBizSoap")]
    public interface svcLibraBizSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FiyatKayitGuncellemeDegistir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool FiyatKayitGuncellemeDegistir(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FiyatKayitlari", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FiyatKayitlari(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FiyatKayitListesi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FiyatKayitListesi(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RutKayitlari", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RutKayitlari(int SalesmanRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RutKayitListesi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RutKayitListesi(int SalesmanRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KampanyaKayitSayisi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string KampanyaKayitSayisi(int SalesmanRef, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KampanyaKayitGuncellemeDegistir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool KampanyaKayitGuncellemeDegistir(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KampanyaKayitlari", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string KampanyaKayitlari(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KampanyaKayitListesi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet KampanyaKayitListesi(int SalesmanRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EkstreTurleri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EkstreTurleri();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NedenListesi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet NedenListesi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MobilGuncellemeKontrol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MobilGuncellemeKontrol(string Referans, int SalesmanRef, string Aygit, string Surum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MobilGuncellemeEkle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MobilGuncellemeEkle(string Referans, int SalesmanRef, string Aciklama);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MobilSiparisNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet MobilSiparisNo(int SalesmanRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MobilSiparisNoYaz", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool MobilSiparisNoYaz(int SalesmanRef, string SonIslem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MobilSiparisYaz", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool MobilSiparisYaz(string SiparisRef, int SalesManRef, string SiparisNo, int FiyatTipi, int MusteriRef, System.DateTime Tarih, decimal Tutar, string Satici, string OdemePlani, string Aciklama1, System.Data.DataSet siparisTablosu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebSiparisYaz", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool WebSiparisYaz(
                    string SiparisRef, 
                    int SiparisTip, 
                    int SalesManRef, 
                    string SiparisNo, 
                    int FiyatTipi, 
                    int MusteriRef, 
                    System.DateTime Tarih, 
                    decimal Tutar, 
                    int OdemePlani, 
                    string Aciklama1, 
                    string Aciklama2, 
                    string Aciklama3, 
                    string Aciklama4, 
                    int SevkRef, 
                    string SiparisiAlan, 
                    bool Taksit, 
                    string MusteriSiparisNo, 
                    bool BakiyeSiparis, 
                    System.Data.DataSet siparisTablosu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebSiparisYaz_Ambarli", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool WebSiparisYaz_Ambarli(
                    string SiparisRef, 
                    int SiparisTip, 
                    int SalesManRef, 
                    int IsyeriNo, 
                    int AmbarNo, 
                    string SiparisNo, 
                    int FiyatTipi, 
                    int MusteriRef, 
                    System.DateTime Tarih, 
                    decimal Tutar, 
                    int OdemePlani, 
                    string Aciklama1, 
                    string Aciklama2, 
                    string Aciklama3, 
                    string Aciklama4, 
                    int SevkRef, 
                    string SiparisiAlan, 
                    bool Taksit, 
                    string MusteriSiparisNo, 
                    bool BakiyeSiparis, 
                    System.Data.DataSet siparisTablosu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MobilZiyaretYaz", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool MobilZiyaretYaz(string Logicalref, int Salesmanref, int Clref, string Tarih, int Barkod, string Nedenref, string Cikis, decimal Kilometre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZiyaretYaz", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ZiyaretYaz(System.Data.DataSet ziyaretTablosu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelfTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SelfTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LBSConnectTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LBSConnectTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LBSDisconnectTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool LBSDisconnectTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaletKontrol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue PaletKontrol(string Barkod, int Hareket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaletRafBarkoduKontrol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PaletRafBarkoduKontrol(string Barkod, string RafRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaletRafBarkoduBilgisi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] PaletRafBarkoduBilgisi(string Barkod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaletRafBarkodu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PaletRafBarkodu(string Barkod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaletBilgileri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PaletBilgileri(string Barkod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaletIcerigi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PaletIcerigi(string Barkod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaletTurBilgileri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PaletTurBilgileri();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaletAgirlikTurGuncelle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool PaletAgirlikTurGuncelle(string Barkod, decimal Agirlik, System.Guid Turu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KutuKontrol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue KutuKontrol(string Barkod, int Hareket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KutuRafBarkodu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string KutuRafBarkodu(string Barkod, string PBarkod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LottanMalzemeGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.Malzeme LottanMalzemeGetir(string Barkod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LottanMiktarGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        decimal LottanMiktarGetir(string Barkod, string RafRef, int MalzemeRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LottanYerDegistirmeMiktarGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        decimal LottanYerDegistirmeMiktarGetir(string Barkod, int MalzemeRef, string SayimRef, string EmirRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LotSeriKontrol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue LotSeriKontrol(string Barkod, int MalzemeRef, int IzlemeTipi, int Hareket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YurtDisiLotSeriKontrol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue YurtDisiLotSeriKontrol(string Barkod, int MalzemeRef, System.Guid EmirRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MalzemeKontrol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.Malzeme MalzemeKontrol(string Barkod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemNoIleOkuAmbarSecimli", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.IsEmri IslemNoIleOkuAmbarSecimli(string IslemNr, int Tip, bool AmbarBilgileri, bool Giris);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayimIslemNoIleOku", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.IsEmri SayimIslemNoIleOku(string IslemNr, int Tip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayimBaslikAciklamaGuncelle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SayimBaslikAciklamaGuncelle(System.Guid Logicalref, string Aciklama);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayimBaslikYaz", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue SayimBaslikYaz(System.Guid LogicalRef, System.DateTime Tarih, int Gambar, int CAmbar, string Aciklama, System.Guid EmirRef, int FisTuru, string IslemNo, string KullaniciAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayimBaslikGuncelle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue SayimBaslikGuncelle(System.Guid LogicalRef, System.DateTime Tarih, int Gambar, int CAmbar, string Aciklama, System.Guid EmirRef, int FisTuru, string IslemNo, string KullaniciAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayimListesi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SayimListesi(string LogicalRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmirListesi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EmirListesi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FisTuruBilgileri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet FisTuruBilgileri(int fisturu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmirsizFisTurleri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EmirsizFisTurleri(bool Giris);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RafSorgulama", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RafSorgulama(string Barkod, string BarkodTipi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ParametreListesi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ParametreListesi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DigerParametreler", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DigerParametreler();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsEmriAmbariGuncelle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsEmriAmbariGuncelle(System.Guid LogicalRef, int AmbarNo, int Tip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayimBittiMi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SayimBittiMi(System.Guid LogicalRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayimSatirSayisi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SayimSatirSayisi(System.Guid LogicalRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayimBaslikKapat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue SayimBaslikKapat(System.Guid LogicalRef, int Hareket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayimBaslikAc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue SayimBaslikAc(System.Guid LogicalRef, int Hareket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayimBaslikOnayla", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue SayimBaslikOnayla(System.Guid LogicalRef, string KullaniciAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayimSatirYaz", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue SayimSatirYaz(System.Guid Logicalref, string Palet, string Kutu, string Seri, decimal Miktar, string Aciklama, System.Guid CRafref, System.Guid GRafref, int Malzemeref, System.Guid Sayimref, int Birim, string KullaniciAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayimSil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue SayimSil(System.Guid Logicalref);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SayimSatirSil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue SayimSatirSil(System.Guid Logicalref, string PaletKodu, string KutuKodu, int MalzemeRef, string Seri, string SatirRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KayitNumarasiAl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string KayitNumarasiAl(int IslemTuru);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbarBilgileri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.Ambar AmbarBilgileri(int AmbarNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SecimliAmbarBilgileri", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.Ambar SecimliAmbarBilgileri(int AmbarNo, int Hareket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SecimliAmbarBilgileriKontrollu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.Ambar SecimliAmbarBilgileriKontrollu(int AmbarNo, int Hareket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RafKontrolu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue RafKontrolu(int AmbarNo, int Hareket, string RafBarkodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AmbarListesi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AmbarListesi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SecimliAmbarListesi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SecimliAmbarListesi(bool Giris, bool Cikis, bool Stok);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KoridorRaflariniAl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.Koridor KoridorRaflariniAl(string RafBarkodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AraTamamlama", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue AraTamamlama(
                    string Terminal, 
                    System.Guid AktifSayimReferansi, 
                    int UretilecekMalzemeRef, 
                    int CiktiBirimReferansi, 
                    bool DepoEntegrasyonuVarMi, 
                    bool ErpEntegrasyonuVarMi, 
                    int AmbarNo, 
                    string SeciliIsEmriNumarasi, 
                    bool PaletZorunlu, 
                    bool KutuZorunlu, 
                    System.Guid GirisRafi, 
                    System.Guid CikisRafi, 
                    string BatchAyraci, 
                    int Izleme, 
                    string KullaniciAdi, 
                    bool PaletTart, 
                    decimal PaletAgirligi, 
                    string PaletKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AraTamamlama_Yeni", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue AraTamamlama_Yeni(System.Guid AktifSayimReferansi, string SeciliIsEmriNumarasi, string KullaniciAdi, decimal PaletAgirligi, string PaletKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsEmrininIsIstasyonunuDegistir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue IsEmrininIsIstasyonunuDegistir(string IsEmriNo, string IsIstasyonuKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsEmrine_Yetkikodu_Ata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue IsEmrine_Yetkikodu_Ata(int IsEmriRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsEmrine_Yetkikodu_Sil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue IsEmrine_Yetkikodu_Sil(int IsEmriRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsEmri_Kapatarak_Kirma_Olustur", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue IsEmri_Kapatarak_Kirma_Olustur(int IsEmriRef, ref int YeniIsEmriRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsEmri_Kapatmadan_Kirma_Olustur", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue IsEmri_Kapatmadan_Kirma_Olustur(int IsEmriRef, ref int YeniIsEmriRef, string KullaniciAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UretimsizKapat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue UretimsizKapat(int IsEmriRef, string KullaniciAdi, string Mesaj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsEmrini_DevamEdiyor_Yap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue IsEmrini_DevamEdiyor_Yap(string IsEmriNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsEmrini_Baslamadi_Yap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sultanlar.UI.QuantumWeb.ReturnValue IsEmrini_Baslamadi_Yap(string IsEmriNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SurumKontrol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SurumKontrol(string App, int Major, int Minor, int Build, int REvision);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CariGuncellemeBitir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CariGuncellemeBitir(int SalesManRef, int ClRef, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CariGuncellemeTamam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CariGuncellemeTamam(int SalesManRef, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EkstreGuncellemeBitir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EkstreGuncellemeBitir(int SalesManRef, int Logicalref, int Clref, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EkstreGuncellemeTamam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool EkstreGuncellemeTamam(int SalesManRef, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MalzemeGuncellemeBitir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool MalzemeGuncellemeBitir(int SalesManRef, int LogicalRef, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MalzemeGuncellemeTamam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool MalzemeGuncellemeTamam(int SalesManRef, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FiyatGuncellemeBitir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool FiyatGuncellemeBitir(int SalesManRef, int Tip, int Itemref, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FiyatGuncellemeTamam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool FiyatGuncellemeTamam(int SalesManRef, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KampanyaGuncellemeBitir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool KampanyaGuncellemeBitir(int SalesManRef, string LogicalRef, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KampanyaGuncellemeTamam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool KampanyaGuncellemeTamam(int SalesManRef, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CariVeriListesi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CariVeriListesi(int SalesmanRef, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CariKayitListesi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CariKayitListesi(int SalesmanRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CariKayitSayisi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CariKayitSayisi(int SalesmanRef, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CariKayitlari", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CariKayitlari(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EkstreVeriListesi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EkstreVeriListesi(int SalesmanRef, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EkstreKayitListesi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet EkstreKayitListesi(int SalesmanRef);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MalzemeKayitListesi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet MalzemeKayitListesi(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MalzemeKayitSayisi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MalzemeKayitSayisi(int SalesmanRef, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MalzemeKayitGuncellemeDegistir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool MalzemeKayitGuncellemeDegistir(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MalzemeKayitlari", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MalzemeKayitlari(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FiyatKayitSayisi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string FiyatKayitSayisi(int SalesmanRef, string Degisiklik);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ErrorCodes errorCodeField;
        
        private string errorDescriptionField;
        
        private string resultField;
        
        private System.Guid headerRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ErrorCodes ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("ErrorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Guid HeaderRef {
            get {
                return this.headerRefField;
            }
            set {
                this.headerRefField = value;
                this.RaisePropertyChanged("HeaderRef");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ErrorCodes {
        
        /// <remarks/>
        Successful,
        
        /// <remarks/>
        CheckError,
        
        /// <remarks/>
        DBError,
        
        /// <remarks/>
        NetError,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Raf : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid logicalrefField;
        
        private string barkodField;
        
        private System.Guid koridorrefField;
        
        private int ambarnoField;
        
        private bool girisField;
        
        private bool cikisField;
        
        private bool stokField;
        
        private bool kapaliField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Logicalref {
            get {
                return this.logicalrefField;
            }
            set {
                this.logicalrefField = value;
                this.RaisePropertyChanged("Logicalref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Barkod {
            get {
                return this.barkodField;
            }
            set {
                this.barkodField = value;
                this.RaisePropertyChanged("Barkod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid Koridorref {
            get {
                return this.koridorrefField;
            }
            set {
                this.koridorrefField = value;
                this.RaisePropertyChanged("Koridorref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Ambarno {
            get {
                return this.ambarnoField;
            }
            set {
                this.ambarnoField = value;
                this.RaisePropertyChanged("Ambarno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool Giris {
            get {
                return this.girisField;
            }
            set {
                this.girisField = value;
                this.RaisePropertyChanged("Giris");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool Cikis {
            get {
                return this.cikisField;
            }
            set {
                this.cikisField = value;
                this.RaisePropertyChanged("Cikis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool Stok {
            get {
                return this.stokField;
            }
            set {
                this.stokField = value;
                this.RaisePropertyChanged("Stok");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool Kapali {
            get {
                return this.kapaliField;
            }
            set {
                this.kapaliField = value;
                this.RaisePropertyChanged("Kapali");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Koridor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid logicalrefField;
        
        private string koduField;
        
        private int ambarnoField;
        
        private bool kapaliField;
        
        private Raf[] raflarField;
        
        private bool raflarAlindiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Logicalref {
            get {
                return this.logicalrefField;
            }
            set {
                this.logicalrefField = value;
                this.RaisePropertyChanged("Logicalref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Kodu {
            get {
                return this.koduField;
            }
            set {
                this.koduField = value;
                this.RaisePropertyChanged("Kodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Ambarno {
            get {
                return this.ambarnoField;
            }
            set {
                this.ambarnoField = value;
                this.RaisePropertyChanged("Ambarno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool Kapali {
            get {
                return this.kapaliField;
            }
            set {
                this.kapaliField = value;
                this.RaisePropertyChanged("Kapali");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public Raf[] Raflar {
            get {
                return this.raflarField;
            }
            set {
                this.raflarField = value;
                this.RaisePropertyChanged("Raflar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool RaflarAlindi {
            get {
                return this.raflarAlindiField;
            }
            set {
                this.raflarAlindiField = value;
                this.RaisePropertyChanged("RaflarAlindi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ambar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ambarNoField;
        
        private string adiField;
        
        private Koridor[] koridorlarField;
        
        private bool koridorlarAlindiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int AmbarNo {
            get {
                return this.ambarNoField;
            }
            set {
                this.ambarNoField = value;
                this.RaisePropertyChanged("AmbarNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Adi {
            get {
                return this.adiField;
            }
            set {
                this.adiField = value;
                this.RaisePropertyChanged("Adi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Koridor[] Koridorlar {
            get {
                return this.koridorlarField;
            }
            set {
                this.koridorlarField = value;
                this.RaisePropertyChanged("Koridorlar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool KoridorlarAlindi {
            get {
                return this.koridorlarAlindiField;
            }
            set {
                this.koridorlarAlindiField = value;
                this.RaisePropertyChanged("KoridorlarAlindi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IsEmri : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid logicalrefField;
        
        private string islemnoField;
        
        private int cAmbarnoField;
        
        private int gAmbarnoField;
        
        private System.DateTime tarihField;
        
        private int tipField;
        
        private int fisTuruField;
        
        private bool durumField;
        
        private Ambar cAmbariField;
        
        private Ambar gAmbariField;
        
        private bool sayimVarField;
        
        private System.Guid sayimRefField;
        
        private bool girisField;
        
        private string aciklamaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Logicalref {
            get {
                return this.logicalrefField;
            }
            set {
                this.logicalrefField = value;
                this.RaisePropertyChanged("Logicalref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Islemno {
            get {
                return this.islemnoField;
            }
            set {
                this.islemnoField = value;
                this.RaisePropertyChanged("Islemno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CAmbarno {
            get {
                return this.cAmbarnoField;
            }
            set {
                this.cAmbarnoField = value;
                this.RaisePropertyChanged("CAmbarno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int GAmbarno {
            get {
                return this.gAmbarnoField;
            }
            set {
                this.gAmbarnoField = value;
                this.RaisePropertyChanged("GAmbarno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime Tarih {
            get {
                return this.tarihField;
            }
            set {
                this.tarihField = value;
                this.RaisePropertyChanged("Tarih");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Tip {
            get {
                return this.tipField;
            }
            set {
                this.tipField = value;
                this.RaisePropertyChanged("Tip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int FisTuru {
            get {
                return this.fisTuruField;
            }
            set {
                this.fisTuruField = value;
                this.RaisePropertyChanged("FisTuru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool Durum {
            get {
                return this.durumField;
            }
            set {
                this.durumField = value;
                this.RaisePropertyChanged("Durum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Ambar CAmbari {
            get {
                return this.cAmbariField;
            }
            set {
                this.cAmbariField = value;
                this.RaisePropertyChanged("CAmbari");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Ambar GAmbari {
            get {
                return this.gAmbariField;
            }
            set {
                this.gAmbariField = value;
                this.RaisePropertyChanged("GAmbari");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool SayimVar {
            get {
                return this.sayimVarField;
            }
            set {
                this.sayimVarField = value;
                this.RaisePropertyChanged("SayimVar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.Guid SayimRef {
            get {
                return this.sayimRefField;
            }
            set {
                this.sayimRefField = value;
                this.RaisePropertyChanged("SayimRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool Giris {
            get {
                return this.girisField;
            }
            set {
                this.girisField = value;
                this.RaisePropertyChanged("Giris");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
                this.RaisePropertyChanged("Aciklama");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Birim : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int logicalrefField;
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Logicalref {
            get {
                return this.logicalrefField;
            }
            set {
                this.logicalrefField = value;
                this.RaisePropertyChanged("Logicalref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Malzeme : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int logicalRefField;
        
        private string searchBarcodeField;
        
        private uint returnUnitRefField;
        
        private string codeField;
        
        private string nameField;
        
        private string bCodeField;
        
        private string bNameField;
        
        private Birim[] unitsField;
        
        private int trackingField;
        
        private bool batchNumberZorunluField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int LogicalRef {
            get {
                return this.logicalRefField;
            }
            set {
                this.logicalRefField = value;
                this.RaisePropertyChanged("LogicalRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SearchBarcode {
            get {
                return this.searchBarcodeField;
            }
            set {
                this.searchBarcodeField = value;
                this.RaisePropertyChanged("SearchBarcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public uint ReturnUnitRef {
            get {
                return this.returnUnitRefField;
            }
            set {
                this.returnUnitRefField = value;
                this.RaisePropertyChanged("ReturnUnitRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BCode {
            get {
                return this.bCodeField;
            }
            set {
                this.bCodeField = value;
                this.RaisePropertyChanged("BCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BName {
            get {
                return this.bNameField;
            }
            set {
                this.bNameField = value;
                this.RaisePropertyChanged("BName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public Birim[] Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
                this.RaisePropertyChanged("Units");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int Tracking {
            get {
                return this.trackingField;
            }
            set {
                this.trackingField = value;
                this.RaisePropertyChanged("Tracking");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool BatchNumberZorunlu {
            get {
                return this.batchNumberZorunluField;
            }
            set {
                this.batchNumberZorunluField = value;
                this.RaisePropertyChanged("BatchNumberZorunlu");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface svcLibraBizSoapChannel : Sultanlar.UI.QuantumWeb.svcLibraBizSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class svcLibraBizSoapClient : System.ServiceModel.ClientBase<Sultanlar.UI.QuantumWeb.svcLibraBizSoap>, Sultanlar.UI.QuantumWeb.svcLibraBizSoap {
        
        public svcLibraBizSoapClient() {
        }
        
        public svcLibraBizSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public svcLibraBizSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svcLibraBizSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public svcLibraBizSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool FiyatKayitGuncellemeDegistir(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik) {
            return base.Channel.FiyatKayitGuncellemeDegistir(SalesmanRef, PageSize, PageIndex, Degisiklik);
        }
        
        public string FiyatKayitlari(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik) {
            return base.Channel.FiyatKayitlari(SalesmanRef, PageSize, PageIndex, Degisiklik);
        }
        
        public System.Data.DataSet FiyatKayitListesi(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik) {
            return base.Channel.FiyatKayitListesi(SalesmanRef, PageSize, PageIndex, Degisiklik);
        }
        
        public string RutKayitlari(int SalesmanRef) {
            return base.Channel.RutKayitlari(SalesmanRef);
        }
        
        public System.Data.DataSet RutKayitListesi(int SalesmanRef) {
            return base.Channel.RutKayitListesi(SalesmanRef);
        }
        
        public string KampanyaKayitSayisi(int SalesmanRef, string Degisiklik) {
            return base.Channel.KampanyaKayitSayisi(SalesmanRef, Degisiklik);
        }
        
        public bool KampanyaKayitGuncellemeDegistir(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik) {
            return base.Channel.KampanyaKayitGuncellemeDegistir(SalesmanRef, PageSize, PageIndex, Degisiklik);
        }
        
        public string KampanyaKayitlari(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik) {
            return base.Channel.KampanyaKayitlari(SalesmanRef, PageSize, PageIndex, Degisiklik);
        }
        
        public System.Data.DataSet KampanyaKayitListesi(int SalesmanRef) {
            return base.Channel.KampanyaKayitListesi(SalesmanRef);
        }
        
        public System.Data.DataSet EkstreTurleri() {
            return base.Channel.EkstreTurleri();
        }
        
        public System.Data.DataSet NedenListesi() {
            return base.Channel.NedenListesi();
        }
        
        public string MobilGuncellemeKontrol(string Referans, int SalesmanRef, string Aygit, string Surum) {
            return base.Channel.MobilGuncellemeKontrol(Referans, SalesmanRef, Aygit, Surum);
        }
        
        public string MobilGuncellemeEkle(string Referans, int SalesmanRef, string Aciklama) {
            return base.Channel.MobilGuncellemeEkle(Referans, SalesmanRef, Aciklama);
        }
        
        public System.Data.DataSet MobilSiparisNo(int SalesmanRef) {
            return base.Channel.MobilSiparisNo(SalesmanRef);
        }
        
        public bool MobilSiparisNoYaz(int SalesmanRef, string SonIslem) {
            return base.Channel.MobilSiparisNoYaz(SalesmanRef, SonIslem);
        }
        
        public bool MobilSiparisYaz(string SiparisRef, int SalesManRef, string SiparisNo, int FiyatTipi, int MusteriRef, System.DateTime Tarih, decimal Tutar, string Satici, string OdemePlani, string Aciklama1, System.Data.DataSet siparisTablosu) {
            return base.Channel.MobilSiparisYaz(SiparisRef, SalesManRef, SiparisNo, FiyatTipi, MusteriRef, Tarih, Tutar, Satici, OdemePlani, Aciklama1, siparisTablosu);
        }
        
        public bool WebSiparisYaz(
                    string SiparisRef, 
                    int SiparisTip, 
                    int SalesManRef, 
                    string SiparisNo, 
                    int FiyatTipi, 
                    int MusteriRef, 
                    System.DateTime Tarih, 
                    decimal Tutar, 
                    int OdemePlani, 
                    string Aciklama1, 
                    string Aciklama2, 
                    string Aciklama3, 
                    string Aciklama4, 
                    int SevkRef, 
                    string SiparisiAlan, 
                    bool Taksit, 
                    string MusteriSiparisNo, 
                    bool BakiyeSiparis, 
                    System.Data.DataSet siparisTablosu) {
            return base.Channel.WebSiparisYaz(SiparisRef, SiparisTip, SalesManRef, SiparisNo, FiyatTipi, MusteriRef, Tarih, Tutar, OdemePlani, Aciklama1, Aciklama2, Aciklama3, Aciklama4, SevkRef, SiparisiAlan, Taksit, MusteriSiparisNo, BakiyeSiparis, siparisTablosu);
        }
        
        public bool WebSiparisYaz_Ambarli(
                    string SiparisRef, 
                    int SiparisTip, 
                    int SalesManRef, 
                    int IsyeriNo, 
                    int AmbarNo, 
                    string SiparisNo, 
                    int FiyatTipi, 
                    int MusteriRef, 
                    System.DateTime Tarih, 
                    decimal Tutar, 
                    int OdemePlani, 
                    string Aciklama1, 
                    string Aciklama2, 
                    string Aciklama3, 
                    string Aciklama4, 
                    int SevkRef, 
                    string SiparisiAlan, 
                    bool Taksit, 
                    string MusteriSiparisNo, 
                    bool BakiyeSiparis, 
                    System.Data.DataSet siparisTablosu) {
            return base.Channel.WebSiparisYaz_Ambarli(SiparisRef, SiparisTip, SalesManRef, IsyeriNo, AmbarNo, SiparisNo, FiyatTipi, MusteriRef, Tarih, Tutar, OdemePlani, Aciklama1, Aciklama2, Aciklama3, Aciklama4, SevkRef, SiparisiAlan, Taksit, MusteriSiparisNo, BakiyeSiparis, siparisTablosu);
        }
        
        public bool MobilZiyaretYaz(string Logicalref, int Salesmanref, int Clref, string Tarih, int Barkod, string Nedenref, string Cikis, decimal Kilometre) {
            return base.Channel.MobilZiyaretYaz(Logicalref, Salesmanref, Clref, Tarih, Barkod, Nedenref, Cikis, Kilometre);
        }
        
        public bool ZiyaretYaz(System.Data.DataSet ziyaretTablosu) {
            return base.Channel.ZiyaretYaz(ziyaretTablosu);
        }
        
        public string SelfTest() {
            return base.Channel.SelfTest();
        }
        
        public string Test() {
            return base.Channel.Test();
        }
        
        public string LBSConnectTest() {
            return base.Channel.LBSConnectTest();
        }
        
        public bool LBSDisconnectTest() {
            return base.Channel.LBSDisconnectTest();
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue PaletKontrol(string Barkod, int Hareket) {
            return base.Channel.PaletKontrol(Barkod, Hareket);
        }
        
        public string PaletRafBarkoduKontrol(string Barkod, string RafRef) {
            return base.Channel.PaletRafBarkoduKontrol(Barkod, RafRef);
        }
        
        public string[] PaletRafBarkoduBilgisi(string Barkod) {
            return base.Channel.PaletRafBarkoduBilgisi(Barkod);
        }
        
        public string PaletRafBarkodu(string Barkod) {
            return base.Channel.PaletRafBarkodu(Barkod);
        }
        
        public System.Data.DataSet PaletBilgileri(string Barkod) {
            return base.Channel.PaletBilgileri(Barkod);
        }
        
        public System.Data.DataSet PaletIcerigi(string Barkod) {
            return base.Channel.PaletIcerigi(Barkod);
        }
        
        public System.Data.DataSet PaletTurBilgileri() {
            return base.Channel.PaletTurBilgileri();
        }
        
        public bool PaletAgirlikTurGuncelle(string Barkod, decimal Agirlik, System.Guid Turu) {
            return base.Channel.PaletAgirlikTurGuncelle(Barkod, Agirlik, Turu);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue KutuKontrol(string Barkod, int Hareket) {
            return base.Channel.KutuKontrol(Barkod, Hareket);
        }
        
        public string KutuRafBarkodu(string Barkod, string PBarkod) {
            return base.Channel.KutuRafBarkodu(Barkod, PBarkod);
        }
        
        public Sultanlar.UI.QuantumWeb.Malzeme LottanMalzemeGetir(string Barkod) {
            return base.Channel.LottanMalzemeGetir(Barkod);
        }
        
        public decimal LottanMiktarGetir(string Barkod, string RafRef, int MalzemeRef) {
            return base.Channel.LottanMiktarGetir(Barkod, RafRef, MalzemeRef);
        }
        
        public decimal LottanYerDegistirmeMiktarGetir(string Barkod, int MalzemeRef, string SayimRef, string EmirRef) {
            return base.Channel.LottanYerDegistirmeMiktarGetir(Barkod, MalzemeRef, SayimRef, EmirRef);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue LotSeriKontrol(string Barkod, int MalzemeRef, int IzlemeTipi, int Hareket) {
            return base.Channel.LotSeriKontrol(Barkod, MalzemeRef, IzlemeTipi, Hareket);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue YurtDisiLotSeriKontrol(string Barkod, int MalzemeRef, System.Guid EmirRef) {
            return base.Channel.YurtDisiLotSeriKontrol(Barkod, MalzemeRef, EmirRef);
        }
        
        public Sultanlar.UI.QuantumWeb.Malzeme MalzemeKontrol(string Barkod) {
            return base.Channel.MalzemeKontrol(Barkod);
        }
        
        public Sultanlar.UI.QuantumWeb.IsEmri IslemNoIleOkuAmbarSecimli(string IslemNr, int Tip, bool AmbarBilgileri, bool Giris) {
            return base.Channel.IslemNoIleOkuAmbarSecimli(IslemNr, Tip, AmbarBilgileri, Giris);
        }
        
        public Sultanlar.UI.QuantumWeb.IsEmri SayimIslemNoIleOku(string IslemNr, int Tip) {
            return base.Channel.SayimIslemNoIleOku(IslemNr, Tip);
        }
        
        public bool SayimBaslikAciklamaGuncelle(System.Guid Logicalref, string Aciklama) {
            return base.Channel.SayimBaslikAciklamaGuncelle(Logicalref, Aciklama);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue SayimBaslikYaz(System.Guid LogicalRef, System.DateTime Tarih, int Gambar, int CAmbar, string Aciklama, System.Guid EmirRef, int FisTuru, string IslemNo, string KullaniciAdi) {
            return base.Channel.SayimBaslikYaz(LogicalRef, Tarih, Gambar, CAmbar, Aciklama, EmirRef, FisTuru, IslemNo, KullaniciAdi);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue SayimBaslikGuncelle(System.Guid LogicalRef, System.DateTime Tarih, int Gambar, int CAmbar, string Aciklama, System.Guid EmirRef, int FisTuru, string IslemNo, string KullaniciAdi) {
            return base.Channel.SayimBaslikGuncelle(LogicalRef, Tarih, Gambar, CAmbar, Aciklama, EmirRef, FisTuru, IslemNo, KullaniciAdi);
        }
        
        public System.Data.DataSet SayimListesi(string LogicalRef) {
            return base.Channel.SayimListesi(LogicalRef);
        }
        
        public System.Data.DataSet EmirListesi() {
            return base.Channel.EmirListesi();
        }
        
        public System.Data.DataSet FisTuruBilgileri(int fisturu) {
            return base.Channel.FisTuruBilgileri(fisturu);
        }
        
        public System.Data.DataSet EmirsizFisTurleri(bool Giris) {
            return base.Channel.EmirsizFisTurleri(Giris);
        }
        
        public System.Data.DataSet RafSorgulama(string Barkod, string BarkodTipi) {
            return base.Channel.RafSorgulama(Barkod, BarkodTipi);
        }
        
        public System.Data.DataSet ParametreListesi() {
            return base.Channel.ParametreListesi();
        }
        
        public System.Data.DataSet DigerParametreler() {
            return base.Channel.DigerParametreler();
        }
        
        public bool IsEmriAmbariGuncelle(System.Guid LogicalRef, int AmbarNo, int Tip) {
            return base.Channel.IsEmriAmbariGuncelle(LogicalRef, AmbarNo, Tip);
        }
        
        public bool SayimBittiMi(System.Guid LogicalRef) {
            return base.Channel.SayimBittiMi(LogicalRef);
        }
        
        public int SayimSatirSayisi(System.Guid LogicalRef) {
            return base.Channel.SayimSatirSayisi(LogicalRef);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue SayimBaslikKapat(System.Guid LogicalRef, int Hareket) {
            return base.Channel.SayimBaslikKapat(LogicalRef, Hareket);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue SayimBaslikAc(System.Guid LogicalRef, int Hareket) {
            return base.Channel.SayimBaslikAc(LogicalRef, Hareket);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue SayimBaslikOnayla(System.Guid LogicalRef, string KullaniciAdi) {
            return base.Channel.SayimBaslikOnayla(LogicalRef, KullaniciAdi);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue SayimSatirYaz(System.Guid Logicalref, string Palet, string Kutu, string Seri, decimal Miktar, string Aciklama, System.Guid CRafref, System.Guid GRafref, int Malzemeref, System.Guid Sayimref, int Birim, string KullaniciAdi) {
            return base.Channel.SayimSatirYaz(Logicalref, Palet, Kutu, Seri, Miktar, Aciklama, CRafref, GRafref, Malzemeref, Sayimref, Birim, KullaniciAdi);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue SayimSil(System.Guid Logicalref) {
            return base.Channel.SayimSil(Logicalref);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue SayimSatirSil(System.Guid Logicalref, string PaletKodu, string KutuKodu, int MalzemeRef, string Seri, string SatirRef) {
            return base.Channel.SayimSatirSil(Logicalref, PaletKodu, KutuKodu, MalzemeRef, Seri, SatirRef);
        }
        
        public string KayitNumarasiAl(int IslemTuru) {
            return base.Channel.KayitNumarasiAl(IslemTuru);
        }
        
        public Sultanlar.UI.QuantumWeb.Ambar AmbarBilgileri(int AmbarNo) {
            return base.Channel.AmbarBilgileri(AmbarNo);
        }
        
        public Sultanlar.UI.QuantumWeb.Ambar SecimliAmbarBilgileri(int AmbarNo, int Hareket) {
            return base.Channel.SecimliAmbarBilgileri(AmbarNo, Hareket);
        }
        
        public Sultanlar.UI.QuantumWeb.Ambar SecimliAmbarBilgileriKontrollu(int AmbarNo, int Hareket) {
            return base.Channel.SecimliAmbarBilgileriKontrollu(AmbarNo, Hareket);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue RafKontrolu(int AmbarNo, int Hareket, string RafBarkodu) {
            return base.Channel.RafKontrolu(AmbarNo, Hareket, RafBarkodu);
        }
        
        public string AmbarListesi() {
            return base.Channel.AmbarListesi();
        }
        
        public string SecimliAmbarListesi(bool Giris, bool Cikis, bool Stok) {
            return base.Channel.SecimliAmbarListesi(Giris, Cikis, Stok);
        }
        
        public Sultanlar.UI.QuantumWeb.Koridor KoridorRaflariniAl(string RafBarkodu) {
            return base.Channel.KoridorRaflariniAl(RafBarkodu);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue AraTamamlama(
                    string Terminal, 
                    System.Guid AktifSayimReferansi, 
                    int UretilecekMalzemeRef, 
                    int CiktiBirimReferansi, 
                    bool DepoEntegrasyonuVarMi, 
                    bool ErpEntegrasyonuVarMi, 
                    int AmbarNo, 
                    string SeciliIsEmriNumarasi, 
                    bool PaletZorunlu, 
                    bool KutuZorunlu, 
                    System.Guid GirisRafi, 
                    System.Guid CikisRafi, 
                    string BatchAyraci, 
                    int Izleme, 
                    string KullaniciAdi, 
                    bool PaletTart, 
                    decimal PaletAgirligi, 
                    string PaletKodu) {
            return base.Channel.AraTamamlama(Terminal, AktifSayimReferansi, UretilecekMalzemeRef, CiktiBirimReferansi, DepoEntegrasyonuVarMi, ErpEntegrasyonuVarMi, AmbarNo, SeciliIsEmriNumarasi, PaletZorunlu, KutuZorunlu, GirisRafi, CikisRafi, BatchAyraci, Izleme, KullaniciAdi, PaletTart, PaletAgirligi, PaletKodu);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue AraTamamlama_Yeni(System.Guid AktifSayimReferansi, string SeciliIsEmriNumarasi, string KullaniciAdi, decimal PaletAgirligi, string PaletKodu) {
            return base.Channel.AraTamamlama_Yeni(AktifSayimReferansi, SeciliIsEmriNumarasi, KullaniciAdi, PaletAgirligi, PaletKodu);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue IsEmrininIsIstasyonunuDegistir(string IsEmriNo, string IsIstasyonuKodu) {
            return base.Channel.IsEmrininIsIstasyonunuDegistir(IsEmriNo, IsIstasyonuKodu);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue IsEmrine_Yetkikodu_Ata(int IsEmriRef) {
            return base.Channel.IsEmrine_Yetkikodu_Ata(IsEmriRef);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue IsEmrine_Yetkikodu_Sil(int IsEmriRef) {
            return base.Channel.IsEmrine_Yetkikodu_Sil(IsEmriRef);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue IsEmri_Kapatarak_Kirma_Olustur(int IsEmriRef, ref int YeniIsEmriRef) {
            return base.Channel.IsEmri_Kapatarak_Kirma_Olustur(IsEmriRef, ref YeniIsEmriRef);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue IsEmri_Kapatmadan_Kirma_Olustur(int IsEmriRef, ref int YeniIsEmriRef, string KullaniciAdi) {
            return base.Channel.IsEmri_Kapatmadan_Kirma_Olustur(IsEmriRef, ref YeniIsEmriRef, KullaniciAdi);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue UretimsizKapat(int IsEmriRef, string KullaniciAdi, string Mesaj) {
            return base.Channel.UretimsizKapat(IsEmriRef, KullaniciAdi, Mesaj);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue IsEmrini_DevamEdiyor_Yap(string IsEmriNo) {
            return base.Channel.IsEmrini_DevamEdiyor_Yap(IsEmriNo);
        }
        
        public Sultanlar.UI.QuantumWeb.ReturnValue IsEmrini_Baslamadi_Yap(string IsEmriNo) {
            return base.Channel.IsEmrini_Baslamadi_Yap(IsEmriNo);
        }
        
        public bool SurumKontrol(string App, int Major, int Minor, int Build, int REvision) {
            return base.Channel.SurumKontrol(App, Major, Minor, Build, REvision);
        }
        
        public bool CariGuncellemeBitir(int SalesManRef, int ClRef, string Degisiklik) {
            return base.Channel.CariGuncellemeBitir(SalesManRef, ClRef, Degisiklik);
        }
        
        public bool CariGuncellemeTamam(int SalesManRef, string Degisiklik) {
            return base.Channel.CariGuncellemeTamam(SalesManRef, Degisiklik);
        }
        
        public bool EkstreGuncellemeBitir(int SalesManRef, int Logicalref, int Clref, string Degisiklik) {
            return base.Channel.EkstreGuncellemeBitir(SalesManRef, Logicalref, Clref, Degisiklik);
        }
        
        public bool EkstreGuncellemeTamam(int SalesManRef, string Degisiklik) {
            return base.Channel.EkstreGuncellemeTamam(SalesManRef, Degisiklik);
        }
        
        public bool MalzemeGuncellemeBitir(int SalesManRef, int LogicalRef, string Degisiklik) {
            return base.Channel.MalzemeGuncellemeBitir(SalesManRef, LogicalRef, Degisiklik);
        }
        
        public bool MalzemeGuncellemeTamam(int SalesManRef, string Degisiklik) {
            return base.Channel.MalzemeGuncellemeTamam(SalesManRef, Degisiklik);
        }
        
        public bool FiyatGuncellemeBitir(int SalesManRef, int Tip, int Itemref, string Degisiklik) {
            return base.Channel.FiyatGuncellemeBitir(SalesManRef, Tip, Itemref, Degisiklik);
        }
        
        public bool FiyatGuncellemeTamam(int SalesManRef, string Degisiklik) {
            return base.Channel.FiyatGuncellemeTamam(SalesManRef, Degisiklik);
        }
        
        public bool KampanyaGuncellemeBitir(int SalesManRef, string LogicalRef, string Degisiklik) {
            return base.Channel.KampanyaGuncellemeBitir(SalesManRef, LogicalRef, Degisiklik);
        }
        
        public bool KampanyaGuncellemeTamam(int SalesManRef, string Degisiklik) {
            return base.Channel.KampanyaGuncellemeTamam(SalesManRef, Degisiklik);
        }
        
        public string CariVeriListesi(int SalesmanRef, string Degisiklik) {
            return base.Channel.CariVeriListesi(SalesmanRef, Degisiklik);
        }
        
        public System.Data.DataSet CariKayitListesi(int SalesmanRef) {
            return base.Channel.CariKayitListesi(SalesmanRef);
        }
        
        public string CariKayitSayisi(int SalesmanRef, string Degisiklik) {
            return base.Channel.CariKayitSayisi(SalesmanRef, Degisiklik);
        }
        
        public string CariKayitlari(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik) {
            return base.Channel.CariKayitlari(SalesmanRef, PageSize, PageIndex, Degisiklik);
        }
        
        public string EkstreVeriListesi(int SalesmanRef, string Degisiklik) {
            return base.Channel.EkstreVeriListesi(SalesmanRef, Degisiklik);
        }
        
        public System.Data.DataSet EkstreKayitListesi(int SalesmanRef) {
            return base.Channel.EkstreKayitListesi(SalesmanRef);
        }
        
        public System.Data.DataSet MalzemeKayitListesi(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik) {
            return base.Channel.MalzemeKayitListesi(SalesmanRef, PageSize, PageIndex, Degisiklik);
        }
        
        public string MalzemeKayitSayisi(int SalesmanRef, string Degisiklik) {
            return base.Channel.MalzemeKayitSayisi(SalesmanRef, Degisiklik);
        }
        
        public bool MalzemeKayitGuncellemeDegistir(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik) {
            return base.Channel.MalzemeKayitGuncellemeDegistir(SalesmanRef, PageSize, PageIndex, Degisiklik);
        }
        
        public string MalzemeKayitlari(int SalesmanRef, int PageSize, int PageIndex, string Degisiklik) {
            return base.Channel.MalzemeKayitlari(SalesmanRef, PageSize, PageIndex, Degisiklik);
        }
        
        public string FiyatKayitSayisi(int SalesmanRef, string Degisiklik) {
            return base.Channel.FiyatKayitSayisi(SalesmanRef, Degisiklik);
        }
    }
}
