//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Sultanlar.WindowsServiceIslemler.selectsalesvbfaC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZwebSelectSalesVbfaBinding", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Zwebs009[]))]
    public partial class ZwebSelectSalesVbfaService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZwebSelectSalesVbfaOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        protected override System.Net.WebRequest GetWebRequest(Uri uri)
        {
            System.Net.HttpWebRequest request = (System.Net.HttpWebRequest)base.GetWebRequest(uri);
            request.KeepAlive = false;
            request.ProtocolVersion = System.Net.HttpVersion.Version10;
            return request;
        }
        
        /// <remarks/>
        public ZwebSelectSalesVbfaService() {
            this.Url = global::Sultanlar.WindowsServiceIslemler.Properties.Settings.Default.Sultanlar_WindowsServiceIslemler_selectsalesvbfaC_ZwebSelectSalesVbfaService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZwebSelectSalesVbfaCompletedEventHandler ZwebSelectSalesVbfaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sap.com/ZwebSelectSalesVbfa", RequestNamespace="urn:sap-com:document:sap:soap:functions:mc-style", ResponseElementName="ZwebSelectSalesVbfaResult", ResponseNamespace="urn:sap-com:document:sap:soap:functions:mc-style", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("EtVbfa", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zwebs009[] ZwebSelectSalesVbfa([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string IDate, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ITime) {
            object[] results = this.Invoke("ZwebSelectSalesVbfa", new object[] {
                        IDate,
                        ITime});
            return ((Zwebs009[])(results[0]));
        }
        
        /// <remarks/>
        public void ZwebSelectSalesVbfaAsync(string IDate, string ITime) {
            this.ZwebSelectSalesVbfaAsync(IDate, ITime, null);
        }
        
        /// <remarks/>
        public void ZwebSelectSalesVbfaAsync(string IDate, string ITime, object userState) {
            if ((this.ZwebSelectSalesVbfaOperationCompleted == null)) {
                this.ZwebSelectSalesVbfaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZwebSelectSalesVbfaOperationCompleted);
            }
            this.InvokeAsync("ZwebSelectSalesVbfa", new object[] {
                        IDate,
                        ITime}, this.ZwebSelectSalesVbfaOperationCompleted, userState);
        }
        
        private void OnZwebSelectSalesVbfaOperationCompleted(object arg) {
            if ((this.ZwebSelectSalesVbfaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZwebSelectSalesVbfaCompleted(this, new ZwebSelectSalesVbfaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zwebs009 {
        
        private string mandtField;
        
        private string vbelvField;
        
        private string posnvField;
        
        private string vbelnField;
        
        private string posnnField;
        
        private string vbtypNField;
        
        private decimal rfmngField;
        
        private bool rfmngFieldSpecified;
        
        private string meinsField;
        
        private decimal rfwrtField;
        
        private bool rfwrtFieldSpecified;
        
        private string waersField;
        
        private string vbtypVField;
        
        private string plminField;
        
        private string taquiField;
        
        private string erdatField;
        
        private string erzetField;
        
        private string matnrField;
        
        private string bwartField;
        
        private string bdartField;
        
        private string plartField;
        
        private string stufeField;
        
        private string lgnumField;
        
        private string aedatField;
        
        private string fktypField;
        
        private decimal brgewField;
        
        private bool brgewFieldSpecified;
        
        private string geweiField;
        
        private decimal volumField;
        
        private bool volumFieldSpecified;
        
        private string volehField;
        
        private string fplnrField;
        
        private string fpltrField;
        
        private float rfmngFloField;
        
        private bool rfmngFloFieldSpecified;
        
        private float rfmngFltField;
        
        private bool rfmngFltFieldSpecified;
        
        private string vrkmeField;
        
        private float abgesField;
        
        private bool abgesFieldSpecified;
        
        private string sobkzField;
        
        private string sonumField;
        
        private string kzbefField;
        
        private decimal ntgewField;
        
        private bool ntgewFieldSpecified;
        
        private string logsysField;
        
        private string wbstaField;
        
        private string cmethField;
        
        private string mjahrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mandt {
            get {
                return this.mandtField;
            }
            set {
                this.mandtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Vbelv {
            get {
                return this.vbelvField;
            }
            set {
                this.vbelvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Posnv {
            get {
                return this.posnvField;
            }
            set {
                this.posnvField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Vbeln {
            get {
                return this.vbelnField;
            }
            set {
                this.vbelnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Posnn {
            get {
                return this.posnnField;
            }
            set {
                this.posnnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VbtypN {
            get {
                return this.vbtypNField;
            }
            set {
                this.vbtypNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Rfmng {
            get {
                return this.rfmngField;
            }
            set {
                this.rfmngField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RfmngSpecified {
            get {
                return this.rfmngFieldSpecified;
            }
            set {
                this.rfmngFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Meins {
            get {
                return this.meinsField;
            }
            set {
                this.meinsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Rfwrt {
            get {
                return this.rfwrtField;
            }
            set {
                this.rfwrtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RfwrtSpecified {
            get {
                return this.rfwrtFieldSpecified;
            }
            set {
                this.rfwrtFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Waers {
            get {
                return this.waersField;
            }
            set {
                this.waersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VbtypV {
            get {
                return this.vbtypVField;
            }
            set {
                this.vbtypVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Plmin {
            get {
                return this.plminField;
            }
            set {
                this.plminField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Taqui {
            get {
                return this.taquiField;
            }
            set {
                this.taquiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Erdat {
            get {
                return this.erdatField;
            }
            set {
                this.erdatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Erzet {
            get {
                return this.erzetField;
            }
            set {
                this.erzetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Matnr {
            get {
                return this.matnrField;
            }
            set {
                this.matnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bwart {
            get {
                return this.bwartField;
            }
            set {
                this.bwartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Bdart {
            get {
                return this.bdartField;
            }
            set {
                this.bdartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Plart {
            get {
                return this.plartField;
            }
            set {
                this.plartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Stufe {
            get {
                return this.stufeField;
            }
            set {
                this.stufeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Lgnum {
            get {
                return this.lgnumField;
            }
            set {
                this.lgnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Aedat {
            get {
                return this.aedatField;
            }
            set {
                this.aedatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Fktyp {
            get {
                return this.fktypField;
            }
            set {
                this.fktypField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Brgew {
            get {
                return this.brgewField;
            }
            set {
                this.brgewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BrgewSpecified {
            get {
                return this.brgewFieldSpecified;
            }
            set {
                this.brgewFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Gewei {
            get {
                return this.geweiField;
            }
            set {
                this.geweiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Volum {
            get {
                return this.volumField;
            }
            set {
                this.volumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VolumSpecified {
            get {
                return this.volumFieldSpecified;
            }
            set {
                this.volumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Voleh {
            get {
                return this.volehField;
            }
            set {
                this.volehField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Fplnr {
            get {
                return this.fplnrField;
            }
            set {
                this.fplnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Fpltr {
            get {
                return this.fpltrField;
            }
            set {
                this.fpltrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float RfmngFlo {
            get {
                return this.rfmngFloField;
            }
            set {
                this.rfmngFloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RfmngFloSpecified {
            get {
                return this.rfmngFloFieldSpecified;
            }
            set {
                this.rfmngFloFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float RfmngFlt {
            get {
                return this.rfmngFltField;
            }
            set {
                this.rfmngFltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RfmngFltSpecified {
            get {
                return this.rfmngFltFieldSpecified;
            }
            set {
                this.rfmngFltFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Vrkme {
            get {
                return this.vrkmeField;
            }
            set {
                this.vrkmeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float Abges {
            get {
                return this.abgesField;
            }
            set {
                this.abgesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AbgesSpecified {
            get {
                return this.abgesFieldSpecified;
            }
            set {
                this.abgesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sobkz {
            get {
                return this.sobkzField;
            }
            set {
                this.sobkzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sonum {
            get {
                return this.sonumField;
            }
            set {
                this.sonumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Kzbef {
            get {
                return this.kzbefField;
            }
            set {
                this.kzbefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Ntgew {
            get {
                return this.ntgewField;
            }
            set {
                this.ntgewField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NtgewSpecified {
            get {
                return this.ntgewFieldSpecified;
            }
            set {
                this.ntgewFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Logsys {
            get {
                return this.logsysField;
            }
            set {
                this.logsysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Wbsta {
            get {
                return this.wbstaField;
            }
            set {
                this.wbstaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cmeth {
            get {
                return this.cmethField;
            }
            set {
                this.cmethField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Mjahr {
            get {
                return this.mjahrField;
            }
            set {
                this.mjahrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ZwebSelectSalesVbfaCompletedEventHandler(object sender, ZwebSelectSalesVbfaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZwebSelectSalesVbfaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZwebSelectSalesVbfaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Zwebs009[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Zwebs009[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591