//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sultanlar.WindowsServiceIslemler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stella.tibet.com.tr:8000/sap/bc/soap/rfc")]
        public string Sultanlar_WindowsServiceIslemler_getcustomersC_ZwebGetCustomersService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_getcustomersC_ZwebGetCustomersService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stella.tibet.com.tr:8000/sap/bc/soap/rfc")]
        public string Sultanlar_WindowsServiceIslemler_getcampaignsC_ZwebGetCampaignsService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_getcampaignsC_ZwebGetCampaignsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stella.tibet.com.tr:8000/sap/bc/soap/rfc")]
        public string Sultanlar_WindowsServiceIslemler_getmaterialpricesC_ZwebGetMaterialPricesService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_getmaterialpricesC_ZwebGetMaterialPricesService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stella.tibet.com.tr:8000/sap/bc/soap/rfc")]
        public string Sultanlar_WindowsServiceIslemler_getmaterialsC_ZwebGetMaterialsService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_getmaterialsC_ZwebGetMaterialsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stella.tibet.com.tr:8000/sap/bc/soap/rfc")]
        public string Sultanlar_WindowsServiceIslemler_getpersonalsC_ZwebGetPersonalsService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_getpersonalsC_ZwebGetPersonalsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stella.tibet.com.tr:8000/sap/bc/soap/rfc")]
        public string Sultanlar_WindowsServiceIslemler_getsalesreportC_ZwebSelectSalesReportService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_getsalesreportC_ZwebSelectSalesReportService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stella.tibet.com.tr:8000/sap/bc/soap/rfc")]
        public string Sultanlar_WindowsServiceIslemler_getdelinvC_ZwebGetDelInvService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_getdelinvC_ZwebGetDelInvService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stella.tibet.com.tr:8000/sap/bc/soap/rfc")]
        public string Sultanlar_WindowsServiceIslemler_selectaccountingC_ZwebSelectAccountingService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_selectaccountingC_ZwebSelectAccountingService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stella.tibet.com.tr:8000/sap/bc/soap/rfc")]
        public string Sultanlar_WindowsServiceIslemler_selectkolietiketC_ZwebSelectKoliEtiketService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_selectkolietiketC_ZwebSelectKoliEtiketService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stella.tibet.com.tr:8000/sap/bc/soap/rfc")]
        public string Sultanlar_WindowsServiceIslemler_selectsalesdeliveryC_ZwebSelectSalesDeliveryService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_selectsalesdeliveryC_ZwebSelectSalesDeliveryServ" +
                    "ice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stella.tibet.com.tr:8000/sap/bc/soap/rfc")]
        public string Sultanlar_WindowsServiceIslemler_selectsalesorderC_ZwebSelectSalesOrderService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_selectsalesorderC_ZwebSelectSalesOrderService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stella.tibet.com.tr:8000/sap/bc/soap/rfc")]
        public string Sultanlar_WindowsServiceIslemler_selectsalestransportC_ZwebSelectSalesTransportService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_selectsalestransportC_ZwebSelectSalesTransportSe" +
                    "rvice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stella.tibet.com.tr:8000/sap/bc/soap/rfc")]
        public string Sultanlar_WindowsServiceIslemler_selectsalesvbfaC_ZwebSelectSalesVbfaService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_selectsalesvbfaC_ZwebSelectSalesVbfaService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://efatura.tibet.com.tr/TIBETeFatura/services/EFaturaInfoPort")]
        public string Sultanlar_WindowsServiceIslemler_efaturaC_EFaturaInfoService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_efaturaC_EFaturaInfoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stella.tibet.com.tr:8000/sap/bc/soap/rfc")]
        public string Sultanlar_WindowsServiceIslemler_selectsalesgoodsmoveC_ZwebSelectSalesGoodsMoveService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_selectsalesgoodsmoveC_ZwebSelectSalesGoodsMoveSe" +
                    "rvice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stella.tibet.com.tr:8000/sap/bc/soap/rfc")]
        public string Sultanlar_WindowsServiceIslemler_selectekstreC_ZwebSelectEkstreService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_selectekstreC_ZwebSelectEkstreService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://test.efatura.tibet.com.tr/TIBETeFatura/services/EFaturaInfoPort")]
        public string Sultanlar_WindowsServiceIslemler_efatura_EFaturaInfoService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_efatura_EFaturaInfoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://stella.tibet.com.tr:8000/sap/bc/soap/rfc")]
        public string Sultanlar_WindowsServiceIslemler_gett179tC_ZwebGetT179tService {
            get {
                return ((string)(this["Sultanlar_WindowsServiceIslemler_gett179tC_ZwebGetT179tService"]));
            }
        }
    }
}
